name: dev pull request

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - dev

jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK v21 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application.yml 파일 만들기
        run: echo '${{ secrets.APPLICATION_PROPERTIES }}' > ./src/main/resources/application.yml

      - name: application-test.yml 파일 만들기
        run: echo '${{ secrets.APPLICATION_TEST_PROPERTIES }}' > ./src/main/resources/application-test.yml

      - name: credentials.json 파일 만들기
        run: echo '${{ secrets.CREDENTIAL_JSON }}' > ./src/main/resources/credentials.json

      - name: 빌드하기 및 테스트 하기
        
        run: ./gradlew clean build
